Change and run test azure-deploy.yml

diff --git a/.github/workflows/azure-deploy.yml b/.github/workflows/azure-deploy.yml
--- a/.github/workflows/azure-deploy.yml
+++ b/.github/workflows/azure-deploy.yml
@@ -18,6 +18,10 @@ jobs:
       - name: Set Working Directory
         run: cd api_sentiment_analysis
 
+      - name: Verify PCA Model
+        run: |
+          ls -al models
+          test -f models/pca_model.pkl || (echo "PCA model file is missing!" && exit 1)
       - name: Set up Python
         uses: actions/setup-python@v4
         with:
