verify if venv work

diff --git a/.github/workflows/azure-deploy.yml b/.github/workflows/azure-deploy.yml
--- a/.github/workflows/azure-deploy.yml
+++ b/.github/workflows/azure-deploy.yml
@@ -11,12 +11,10 @@ on:
 jobs:
   test:
     runs-on: ubuntu-latest
+
     steps:
       - name: Checkout Code
         uses: actions/checkout@v3
-
-      - name: Set Working Directory
-        run: cd api_sentiment_analysis
 
       - name: List Repository Files
         run: ls -al
@@ -25,29 +23,29 @@ jobs:
         uses: actions/setup-python@v4
         with:
           python-version: "3.10"
+
       - name: Create Virtual Environment
         run: |
           python -m venv venv
           source venv/bin/activate
           pip install --upgrade pip
-          
+        working-directory: ./api_sentiment_analysis
+
       - name: Install Dependencies
         run: |
-          python -m venv venv
           source venv/bin/activate
-          pip install --upgrade pip
           pip install -r requirements.txt
           pip install joblib scikit-learn
         working-directory: ./api_sentiment_analysis
 
-      # Étape 5 : Vérification des artefacts nécessaires
       - name: Verify Models
         run: |
-          test -f api_sentiment_analysis/models/pca_model.pkl || (echo "PCA model file is missing!" && exit 1)
-          test -d api_sentiment_analysis/models/mlflow_model || (echo "MLflow model folder is missing!" && exit 1)
+          test -f models/pca_model.pkl || (echo "PCA model file is missing!" && exit 1)
+          test -d models/mlflow_model || (echo "MLflow model folder is missing!" && exit 1)
+        working-directory: ./api_sentiment_analysis
 
-      # Étape 6 : Exécuter les tests
       - name: Run Tests
         run: |
           source venv/bin/activate
           pytest tests/ --maxfail=5 --disable-warnings
+        working-directory: ./api_sentiment_analysis
